import { Manrope } from "next/font/google";
import "./globals.css";

export const manrope = Manrope({
  weight: ["800", "700", "600", "500", "400", "300", "200"],
  subsets: ["latin"],
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Casa Mobiliada",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
